### ISSUE TITLE
[BUG]: Regression in OAuth Fetch Tools API between v1.0.0-RC-2 and v1.0.0 – 'list' object has no attribute 'split'

### ISSUE THREAD

**Issue by vksinha10** [IBM/mcp-context-forge#4920]
We are seeing a regression in MCP Gateway OAuth tool fetching behavior after upgrading from version 1.0.0-RC-2 to version 1.0.0.

Issue Summary:
The endpoint /oauth/fetch-tools/{gatewayId} works successfully in version 1.0.0-RC-2, but fails in version 1.0.0 with the following error:

Error Response:
{
"detail": "Failed to fetch tools: Failed to fetch tools after OAuth: 'list' object has no attribute 'split'"
}

Environment:

MCP Gateway Version (Working): 1.0.0-RC-2
MCP Gateway Version (Failing): 1.0.0
Transport: STREAMABLEHTTP
Authentication Type: OAuth (authorization_code grant)

Gateway Registration Payload:
{
"name": "foo-bar-mcp",
"url": "https://foo-bar.com/mcp/data-search",
"description": "Foo Bar MCP With DCR",
"transport": "STREAMABLEHTTP",
"enabled": true,
"auth_type": "oauth",
"oauth_config": {
"grant_type": "authorization_code",
"issuer": "https://foo-bar.com/oauth",
"redirect_uri": "https://foo-bar.com/oauth/callback",
"scopes": [
"activity",
"admin",
"agents",
"announcements",
"answers",
"auth_token_creator",
"chat",
"collections",
"content_hiding",
"feed",
"feedback",
"insights",
"mcp",
"offline_access",
"openid",
"people",
"pins",
"search",
"shortcuts",
"summarize",
"tools",
"verification"
]
}
}

Behavior Comparison:

Version: 1.0.0-RC-2
Request:
GET /oauth/fetch-tools/{gatewayId}

Response:

HTTP 200 OK
Tools fetched successfully
Version: 1.0.0
Request:
GET /oauth/fetch-tools/{gatewayId}

Response:
{
"detail": "Failed to fetch tools: Failed to fetch tools after OAuth: 'list' object has no attribute 'split'"
}

Observation:
This appears to be a regression introduced in version 1.0.0. Based on the error, it looks like the OAuth flow may now be attempting to call .split() on the scopes field while the payload provides scopes as a JSON list/array instead of a comma-separated string.

Since the same gateway configuration works in 1.0.0-RC-2 and fails in 1.0.0, this seems to indicate a compatibility or parsing issue introduced in the GA release.

Please let us know if additional logs or reproduction steps are needed.

**Comment by rakdutta** [comment]
## ✅ Already Fixed
  
  This issue was resolved in commit `48ae6ba69` (PR #4594, merged May 10, 2026).
  
  The `'list' object has no attribute 'split'` error when using `scopes` as a JSON array is fixed in current `main` branch.
  
  ### Action Required
  Upgrade to latest `main` or wait for v1.0.2+ release.
  
  Closing as already fixed. Please reopen if still encountering this on latest version.
