### ISSUE TITLE
ObservabilityServiceAdapter passes db= instead of obs_db= to ObservabilityService.start_span/end_span, causing TypeError on every span

### ISSUE THREAD

**Issue by sgalij** [IBM/mcp-context-forge#6600]
### 🐞 Bug Summary

`ObservabilityServiceAdapter.start_span()` and `ObservabilityServiceAdapter.end_span()`
(`mcpgateway/plugins/observability_adapter.py`) call `ObservabilityService.start_span()` /
`ObservabilityService.end_span()` with a `db=` keyword argument, but those methods were
renamed to accept `obs_db=` as part of the independent-session pattern from #3883 (see
`AGENTS.md` → *Observability Transaction Behavior*). As a result, every span
start/end routed through the plugin adapter raises a `TypeError`, which is swallowed by
a broad `except Exception` and only surfaces as a WARNING log — so no spans are ever
recorded for plugin/tool invocations, and the failure goes unnoticed in production.

Note: this bug is also reported under issue 174 in CPEX repo: 
https://github.com/contextforge-org/cpex/issues/174

---

### 🧩 Affected Component

- [x] `mcpgateway` - API
- [ ] `mcpgateway` - UI (admin panel)
- [ ] `mcpgateway.wrapper` - stdio wrapper
- [ ] Federation or Transports
- [ ] CLI, Makefiles, or shell scripts
- [ ] Container setup (Docker/Podman/Compose)
- [ ] Other (explain below)

Specifically: plugin framework observability integration (`mcpgateway/plugins/observability_adapter.py`), introduced in #3140.

---

### 🔁 Steps to Reproduce

1. Enable a plugin that triggers observability spans via `ObservabilityServiceAdapter` (e.g. any plugin executed through the plugin framework's executor with observability enabled).
2. Invoke a tool/resource/prompt so the plugin executor calls `start_span()` / `end_span()` on the adapter.
3. Observe the application logs.

---

### 🤔 Expected Behavior

`start_span()` should successfully create a span and return a span ID, and `end_span()`
should update that span with the final status — both persisted via `ObservabilityService`
without error.

Instead, both calls fail immediately with a `TypeError` because of the wrong keyword
argument name (`db` vs `obs_db`), so no span data is ever written, and the error is only
visible as a WARNING-level log line.

---

### 📓 Logs / Error Output

```json
{"asctime": "2026-09-03T10:48:33", "name": "mcpgateway.plugins.observability_adapter",
"levelname": "WARNING", "message": "ObservabilityServiceAdapter.start_span failed:
ObservabilityService.start_span() got an unexpected keyword argument 'db'",
"@timestamp": "2026-09-03T08:48:33.927725Z", "hostname": "LAPTOP-1RV651KG",
"process_id": 6051, "request_id": "9fd46a88774744ccb02027f071fa7c0a",
"trace_id": "678577fdbe81ffc1aaf68a9f90f45523", "span_id": "7cdc9c34f19d51e3",
"trace_flags": "03"}
